name: light_lux
description: A new Flutter project.

publish_to: "none"

version: 1.0.1-F+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.0
  light: ^1.0.0
  url_launcher: ^5.7.10
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
